version: '3.9'
services:
  postgres:
    image: postgres:14.8
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psotgres
      POSTGRES_DB: fastifytut
    ports:
      - '5432:5432'
volumes:
  postgres:
